all: principal

.PHONY: all clean

principal:
	@g++ -Wall main.cpp src/Datatypes/DTCalificacion.cpp src/Datatypes/DTEmpleado.cpp src/Datatypes/DTFecha.cpp src/Datatypes/DTHabitacion.cpp src/Datatypes/DTHostal.cpp src/Datatypes/DTHuesped.cpp src/Datatypes/DTReserva.cpp src/Datatypes/DTReservaGrupal.cpp src/Datatypes/DTReservaIndividual.cpp src/Datatypes/DTUsuario.cpp src/Classes/Calificacion.cpp src/Classes/controladorEstadiaReserva.cpp src/Classes/controladorHostal.cpp src/Classes/controladorUsuario.cpp src/Classes/Empleado.cpp src/Classes/Estadia.cpp src/Classes/Fabrica.cpp src/Classes/FechaSistema.cpp src/Classes/Habitacion.cpp src/Classes/Hostal.cpp src/Classes/Huesped.cpp src/Classes/Reserva.cpp src/Classes/ReservaGrupal.cpp src/Classes/ReservaIndividual.cpp src/Classes/Usuario.cpp src/Datatypes/DTEstadia.cpp src/Classes/Comentario.cpp -o principal
clean:
	@rm -f *.o principal